### ISSUE TITLE
Revise frontend based on Dan's suggestions

### ISSUE THREAD

**Issue by istwu** [wmgeolab/scope#142]
Dashboard (rename to Home?) (pushed to next semester)

- [ ] link to query page
- [ ] page/section for saved queries (persistent)
- [ ] create display for statistics about overall database (eg records added in last 24h, total records added, etc)
- [ ] add charts, cumulative numbers

Results (pushed to next semester, a lot of it relies on backend/AI teams)

- [ ] each query should have title, url, source time (all clickable), NLP/ML generated synopsis, actor, latitude/longitude, 
- [ ] create filter/sort by for time, lat/long, number of actors, etc
- [ ] add feature to select rows and save articles into workspace
- [ ] generate query id based on query itself (hash title)
- [ ] search widget?

Workspace(s) (pushed for next semester)

- [ ] make them unique for every user; each user can have multiple workspaces
- [ ] users can make, rename, edit, delete
- [ ] export articles into some form of dataset?
- [ ] incl widgets from results page???

**Comment by joegenius98** [comment]
Current TODOs:

- [] Separate MVP tasks vs. non-MVP
- [] Create issues/sub-issues for MVP tasks

**Comment by joegenius98** [comment]
Vision for MVP: add a filter for the result (by date, query, name, authors), add columns for the sypnosis,

Pagination for the frontend & backend. Pagination is about having different pages so that the sources and results are split up on other pages.  

Map and adding latitude, longitude data can also be done for later. We could implement basic sorting for now—sort by date, query, title, etc. 

So, the querying in the backend is done alright; it's just that the frontend needs to increase its pagination size so that all the results are actually displayed. 


"Show only selected ones" for next month, which won't be useful until workspaces are implemented. 

Dashboard widgets can be implemented later; for now, we can just put in a description of how to use SCOPE.


Dan wants "queries" and "results" to be buttons you can click, instead of just "queries" now. 

Placement of the button for the "GitHub" maybe.
