### ISSUE TITLE
Prettify extraction checkout page

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#37]
This one depends on what we decide for #35 . 

- [x] Don't display the source html content, and nicer overall layout, eg basic source info incl. url at the top, quote Extract input forms on the bottom? 
- [x] Depending on #35, how to display/organize hierarchical input forms where there can be one or more Observations/Facts, each linked to a list of one or more Extract quotes? 
- [ ] Nicer delete button.

**Comment by micrittenden** [comment]
I think we should also add a "Save" button. As of now, if the checkout user navigates away from the page without submitting I believe their changes are not saved and they would have to retype. There may be times when the user needs to save their work halfway (then turn off their computer and leave to go get dinner or something) but the extracts aren't ready to be submitted. The "Save" button should make changes to the database but not send it forward to the next module.

Also, if a source has already been "extracted," if someone else goes to extract it a second time, should they be prompted "Are you sure you want to extract this source again?" Maybe this is something to go into future iterations, not the bare-bones version.

I think as they are displayed right now (a plain vertical list) is great. We should treat the extracts as independent until the Triangulating module. Maybe we should have a second field which gives the extract a short name? This name could help when users are navigating the Triangulating module (since it gives immediate context, which some quotes may not have consistently).

Also, it may be not suited to comment here, but should the Triangulating module allow extracted quotes to be referenced by multiple events? Sometimes a quote may reference the building of dams at multiple locations within the same sentence. How do we handle when events are right next to each other in the text?

**Comment by karimbahgat** [comment]
Very much agree about the save button, think i added it to one of the other task issues. 

I don’t think we should think about multiple users extracting from the same source yet, maybe down the line. 

Interesting, i do think an extra extract field with a short name for providing context («description» or «summary») could make sense. Just to be clear though, could you give an example of some exteacts, what a user might input for their short names, and how this would help for triangulation? 

Yes i think an extract should be able to be referenced by multiple events, precisely because of common situations where many events are listed in a single sentence. I think this would be a manytomany relationship, where each observation can be linked to one or more extracts from the list of all extracts, without any exclusive ownership to each extract. So an extract mentioning multiple dams, would simply be referenced by multiple events linking to the same extract.

**Comment by micrittenden** [comment]
Currently rethinking the idea of hierarchical ordering and what is the best way to pass along information between the modules... Should talk more on Friday about this.

**Comment by karimbahgat** [comment]
Since we decided on the extraction module to deal with a flat list of extracts, the current setup seems fine and functional for the purpose of the prototype, so that we can focus on the more important parsing module instead. We can do additional prettyfication later.
