### ISSUE TITLE
Allow checking out each Extract and create the parsing interface

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#40]
Parsing or coding means populating structured model instances and field information with information, ie saving a checked out Extract creates an Activity instance with a OneToOneField linking to that Extract, populated with its various fields, eg Actor, date, Locations, etc. We probably need to discuss the details of this more. 

This depends on #35 , ie do we checkout and code each individual quote Extract models, or do we checkout and code Observation/Fact models based on all its related Extracts.

**Comment by micrittenden** [comment]
In line with your thoughts and my further suggestions from issue 35, I believe the Extracting and Triangulating modules have a many-to-one connection; the Triangulating to Deconflicting modules have a one-to-one connection; and the Deconflicting to Parsing modules have a one-to-one connection.
Since neither the Triangulating nor Deconflicting modules are absolutely necessary to a parsing workflow, I think the outputs from the Extracting, Triangulating, and Deconflicting modules should all be of the same structure (just different lengths). If the Parsing module receives something of length > 1 (meaning it went from Extracting to Triangulating and skipped Deconflicting), then the automated version of the module should first concatenate the text. If we follow this approach, I don't think there would be any data structure-based errors in the workflow.

**Comment by micrittenden** [comment]
I've made progress toward this. Rn, there is a bug with rendering the ActivityForm on the extract parsing page and a bug with tracking current_user (unclear if things are being officially and exclusively checked out)

**Comment by micrittenden** [comment]
On the last step to the barebones. Need two things: (1) the changes are saving to db, but not the form; (2) a more discreet way of passing the extract id through the ActivityForm than having an initial value -- any way to do this behind the scenes?

**Comment by micrittenden** [comment]
I'm going to close this and create two new more specific issues for those described above.
