### ISSUE TITLE
Make sure that manually adding a new source actually works

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#42]

**Comment by micrittenden** [comment]
This is the error it currently returns:
ValueError: The view sourcing.views.source_add didn't return an HttpResponse object. It returned None instead.

**Comment by micrittenden** [comment]
Fixed by first adding `return render(request, 'templates/sourcing/source_add.html', {'form':form})` below the print statement in source_add view on views.py.

Now, it would no longer return None. Instead, it returned a new error:
<ul class="errorlist"><li>current_user<ul class="errorlist"><li>This field is required.</li></ul></li></ul>

So, added `blank=True` to the arguments for current_user in the Source model on models.py, and went back to remove the line I'd previously added to views.py, and it worked.

**Comment by karimbahgat** [comment]
Yep, that was me being lazy not looking fully into how to handle and display invalid forms, and might need to be fixed other places too :P And good fix with blank=True, as the form equivalent of null=True!
